### ISSUE TITLE
Doesn't compile on TeX Live 2015

### ISSUE THREAD

**Issue by blipp** [Yannoik/tex#1]
I just found this project because I read the ZaPF reports. Nice idea, thanks for sharing. However, I can't compile it. pdflatex gives me:

```
 [53] (./Einfuehrung.vrb) [54] (./Einfuehrung.vrb) [55] (./Einfuehrung.vrb)
[56] (./Einfuehrung.vrb
! Extra }, or forgotten \endgroup.
\endframe ->\egroup 
                    \begingroup \def \@currenvir {frame}
l.14  \end{frame}

? 
```

See also https://www.overleaf.com/3732415hhzzwq where I imported the project as a test.

On the first sight it looks like a problem with uncover around a tabular environment.

**Comment by Yannoik** [comment]
forget the old version, better version with new features: 
https://github.com/latex-intro/latex-intro
